Language improvements
Skouat/ext_paypal_donation pull request #53
Opened 2017-08-09 21:47 UTC by kasimi

Some more improvements.

2017-08-09 23:11 UTC, Skouat requested changes
Hi kasimi,

Many thanks for this big review.

Before I approve this PR, please can you rebase your branch and fix the 2 highlighted points?

2017-08-09 23:11 UTC, Skouat commented on language/fr/donate.php
> +	'CURL_ERROR'              => 'Erreur cURL: %s',
French typo requires a unbreakable space before the `:`
You can find this chars in each french language file.
eg: https://github.com/Skouat/ext_paypal_donation/blob/749f3016972d42f492fc96dba4b10a5ed003c946/language/fr/donate.php#L34

The nbspace can be find between the french quotation marks (`« »`)

Or, you can use the previous lang keys and simply add ` %s` after `:` withour remove the nbspace already in place before your change.

2017-08-09 23:11 UTC, Skouat commented on language/fr/donate.php
> +	'FSOCK_ERROR'             => 'Erreur fsockopen: %s',
same as comment above.
the `:` must be preceded with a nbspace.

2017-08-10 18:46 UTC, kasimi commented
Thanks for the feedback. Let me know if there's anything else that needs to be fixed.

2017-08-10 19:46 UTC, Skouat approved these changes

2017-08-10 19:48 UTC, merged

2017-08-11 07:29 UTC, Galixte commented
Salut @Skouat ma curiosité me démange. ^^ Pourquoi tu t’embêtes à lui demander cette correction alors que tu pourrais fusionner le PR puis faire un commit correctif après ?

Est-ce qu’il y a un outil de contrôle tel Travis qui va détecter une erreur ou es-tu autant pointilleux avec tes contributeurs que cela ne pourrait en être autrement ?

2017-08-11 12:24 UTC, Skouat commented
Salut @Galixte,

Il n'y a pas de raisons techniques. Juste de la bonne logique.

Effectivement j'aurais pu corriger par la suite. Mais l'intérêt d'accepter des contributions externes c'est que ces dernières ne nécessitent pas à ce que l'on repasse derrière une fois validées. Autant que les contributions soient clean dès la 1ère validation.

2017-08-14 04:20 UTC, Galixte commented
Merci.